### ISSUE TITLE
Site roadmap

### ISSUE THREAD

**Issue by ky28059** [gunnsec/events-app#1]
This is basically a big todo list for what needs to be worked on before we can start publicizing this for student use.

### Whole site
- [ ] Configure weebly DNS settings to allow vercel to deploy this to `events.gunnsec.org` (need to talk to Hall as I can't access the DNS page on my account)
- [ ] Replace default vercel favicon
- [ ] Support dark mode?
- [ ] Confirm whether outreach wants vlogs hosted on a website

### Index page (`/`)
- [ ] Make the index page (see sketch)
- [ ] Link feedback form? (slack)

### Events page (`/events`)
- [ ] Fill out events on spreadsheet (ask Michael & Liang)
- [ ] Think about how to display event subpages

### API docs (`/docs`)
- [ ] Make custom API docs (see WATT api docs for provided info, github docs for general layout / style)

### App page (`/app`)
- [ ] Come up with how data will be parsed for the app (ie. how will events be implemented?)
- [ ] UI -- currently only the hoco page (and a concept for a ping pong tourney page) exist; how should "normal" events look? how should days with no events look? should users be able to switch between days and if so, where will the date selector be?

**Comment by ky28059** [comment]
Also, we should decide whether an app would be helpful. I think we can release this without the `/app` features (since those will take a lot of work to implement) and if we decide to do so we can continue working on it and release the app later in the year.
